### ISSUE TITLE
Two bokeh event connection

### ISSUE THREAD

**Issue by mtunami** [ash2shukla/streamlit-bokeh-events#5]
Hello, 

I tried to connect a bokeh button to a datatable with checkbox so that user can select the ones to perform operation.

![image](https://user-images.githubusercontent.com/85927542/122012917-577d9a00-cdc6-11eb-8de5-a8e1643cf46c.png)

How can it be possible to connect two bokeh events in streamlit?

**Comment by ash2shukla** [comment]
I am not sure whether I understood your question properly, but from what I understand, you are expecting to do some processing based on 2 emitted events. 
The streamlit_bokeh_events function does this out of the box for you as the return value is a dictionary keyed by event ids,
Just make sure that distinct events have distinct ids and u should be good to go.
