### ISSUE TITLE
Bokeh version is not matching with Streamlit as of 1.2.0

### ISSUE THREAD

**Issue by willhuang1997** [ash2shukla/streamlit-bokeh-events#9]
Hi @ash2shukla ,

It looks like looking at your `package.json`, you currently have bokeh==2.0.0. As of Streamlit 1.2.0 release, we currently are only supporting bokeh version 2.4.1 for the latest features and the fact that bokeh JS and python versions must match. The streamlit team is kindly asking if you could upgrade your `package.json` to 2.4.1. 

Thanks,

William

**Comment by ash2shukla** [comment]
@willhuang1997  Fixed in 0.1.3
